### ISSUE TITLE
Some improvements and recommendations

### ISSUE THREAD

**Issue by nikVile** [justdprroz/silaeder-vpn#5]
_I understand that the product is still in development 
and many minor issues/shortcomings will be solved in the process. 
I just want to help with the development, so I'll point out some of them._

**Some problems I have encountered:**

1. login screen webpage moves up-down a bit.
2. "Не можете войти?" button redirects the user to the support communication webpage. Then if you click the "Отправить" button, the site displays only a 404 error. Also on the communication support webpage there are buttons "Silaeder VPN" , "Control Panel" and "Support". When clicked, the first two redirect the user to the login screen, the third one is not clickable at all.
3. The buttons "Silaeder VPN" and "Панель управления" always redirect the user to the same webpage.
4. I would like the tab of the site where I am now to somehow stand out from the others.
5. On the main page of the site there are configs available to us, as well as peers and server data directly. You should slightly expand the area for displaying them so that private and public keys are displayed in one line.
6. Also on the main page of the site there is a button with real name, which redirects the user to the webpage of the nickname and password settings,  I think it would be more convenient to replace it with the "Настройки" button. 
7. On the settings web page, our nickname is displayed twice. One of the times it is displayed as a non-clickable button.
8. And finally, I would not refuse the English localization.

So, that's all for now. If you have any questions about the text above:
**Telegram: nikVile
Mail: nik.shishkin.b@gmail.com**

**Comment by justdprroz** [comment]
Thank you for your issues.

We will explore them and fix them.

Also we will notify you about fixes and features requests as soon as possible.

**Comment by justdprroz** [comment]
I solved some of issues that you mentioned, you can check it out

**Comment by nikVile** [comment]
I'm glad you took the time to do this, now your site looks better. 

I found another thing that you can fix: on the main and settings webpages, the sections of the site are displayed on the left. But on the support webpage they are displayed on the right. I think you should move them to one side.

**Comment by justdprroz** [comment]
Thank you for mentioning this, I solved it, you can check it.

Also, I would recommend you create new issues for everything you want to write.
